{% set name = "strawberry-graphql" %}
{% set version = "0.114.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/strawberry-graphql-{{ version }}.tar.gz
  sha256: 04971a35884fa78ede70c633d7dfff66de957ea811d175d654eb7f8abd5952c9

build:
  entry_points:
    - strawberry = strawberry.cli:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - poetry >=0.12
  run:
    - backports.cached-property >=1.0.1,<2.0.0
    - click >=7.0,<9.0
    - graphql-core >=3.2.0,<3.3.0
    - pygments >=2.3,<3.0
    - python >=3.7
    - python-dateutil >=2.7.0,<3.0.0
    - python-multipart >=0.0.5,<0.0.6
    - typing_extensions >=3.7.4,<5.0.0

test:
  imports:
    - strawberry
  commands:
    - pip check
    - strawberry --help
  requires:
    - pip

about:
  home: https://strawberry.rocks/
  summary: A library for creating GraphQL APIs
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/strawberry-graphql/strawberr
  doc_url: https://strawberry.rocks/docs

extra:
  recipe-maintainers:
    - cshaley
