{% set version = "0.192.1" %}

package:
  name: strawberry-graphql-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/strawberry-graphql/strawberry_graphql-{{ version }}.tar.gz
  # the SHA256 gets updated by the bot
  sha256: 00f8d922aad72997766622c939b57a12720f4208b46d3a258993f305757d3b92

build:
  # the build number gets reset by the bot
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

outputs:
  - name: strawberry-graphql
    build:
      noarch: python
      script:
        - {{ PYTHON }} {{ RECIPE_DIR }}/update_recipe.py --check
        - {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed --no-build-isolation
      entry_points:
        - strawberry = strawberry.cli:run
    requirements:
      host:
        - jinja2
        - pip
        - poetry >=0.12
        - python >=3.7
        - tomli
      run:
        - python >=3.7
        - astunparse 1.*
        - backports.cached-property 1.*
        - graphql-core 3.2.*
        - python-dateutil 2.*
        - typing-extensions >=4.5.0
    test:
      imports:
        - strawberry
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-aiohttp
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - aiohttp 3.*
    test:
      imports:
        - strawberry
        - strawberry.aiohttp
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with aiohttp)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-asgi
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - python-multipart >=0.0.5,<0.0.7
        - starlette >=0.18.0
    test:
      imports:
        - strawberry
        - strawberry.asgi
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with asgi)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-debug
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - libcst >=0.4.7
        - rich >=12.0.0
    test:
      imports:
        - strawberry
        # TODO: import test for debug
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with debug)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-debug-server
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - libcst >=0.4.7
        - pygments 2.*
        - python-multipart >=0.0.5,<0.0.7
        - rich >=12.0.0
        - starlette >=0.18.0
        - typer >=0.7.0
        - uvicorn >=0.11.6,<0.22.0
    test:
      imports:
        - strawberry
        # TODO: import test for debug-server
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with debug-server)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-django
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - asgiref 3.*
        - django >=3.2
    test:
      imports:
        - strawberry
        - strawberry.django
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with django)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-channels
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - asgiref 3.*
        - channels >=3.0.5
    test:
      imports:
        - strawberry
        - strawberry.channels
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with channels)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-flask
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - flask >=1.1
    test:
      imports:
        - strawberry
        - strawberry.flask
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with flask)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-opentelemetry
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - opentelemetry-api <2
        - opentelemetry-sdk <2
    test:
      imports:
        - strawberry
        - strawberry.extensions.tracing
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with opentelemetry)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-pydantic
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - pydantic <2
    test:
      imports:
        - strawberry
        - strawberry.experimental.pydantic
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with pydantic)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-sanic
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - sanic >=20.12.2
    test:
      imports:
        - strawberry
        - strawberry.sanic
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with sanic)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-fastapi
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - fastapi >=0.65.2
        - python-multipart >=0.0.5,<0.0.7
    test:
      imports:
        - strawberry
        - strawberry.fastapi
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with fastapi)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-chalice
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - chalice 1.*
    test:
      imports:
        - strawberry
        - strawberry.chalice
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with chalice)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-cli
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - libcst >=0.4.7
        - pygments 2.*
        - rich >=12.0.0
        - typer >=0.7.0
    test:
      imports:
        - strawberry
        - strawberry.cli
      commands:
        - pip check
        - strawberry --help
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with cli)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-starlite
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - starlite >=1.48.0
    test:
      imports:
        - strawberry
        - strawberry.starlite
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with starlite)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs

  - name: strawberry-graphql-with-pyinstrument
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("strawberry-graphql", max_pin="x.x.x") }}
        - pyinstrument >=4.0.0
    test:
      imports:
        - strawberry
        - strawberry.extensions.pyinstrument
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with pyinstrument)
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/strawberry-graphql/strawberry
      doc_url: https://strawberry.rocks/docs


about:
  home: https://strawberry.rocks
  summary: A library for creating GraphQL APIs
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/strawberry-graphql/strawberry
  doc_url: https://strawberry.rocks/docs

extra:
  feedstock-name: strawberry-graphql
  recipe-maintainers:
    - cshaley
    - thewchan
    - bollwyvl
