# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.269.0"

recipe:
  name: strawberry-graphql
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/strawberry-graphql/strawberry_graphql-${{ version }}.tar.gz
  # the SHA256 gets updated by the bot
  sha256: 67d5dd832a056e755fccb3a0d8476a710c9552d6199505d41d5357580bcde2ea

build:
  # the build number gets reset by the bot
  number: 0

outputs:
  - package:
      name: strawberry-graphql
    build:
      noarch: python
      script:
        - ${{ PYTHON }} ${{ RECIPE_DIR }}/test_recipe.py
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
      python:
        entry_points:
          - strawberry = strawberry.cli:run
    requirements:
      host:
        - jinja2
        - pip
        - poetry >=0.12
        - poetry-core
        - python ${{ python_min }}.*
        - tomli
      run:
        - python >=${{ python_min }}
        - graphql-core >=3.2.0,<3.4.0
        - packaging >=23
        - python-dateutil 2.*
        - typing-extensions >=4.5.0
        # fix after https://github.com/conda-forge/astunparse-feedstock/pull/15
        - wheel
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports: strawberry

  - package:
      name: strawberry-graphql-with-aiohttp
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - aiohttp 3.*
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            - strawberry.aiohttp
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with aiohttp)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-asgi
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - python-multipart >=0.0.7
        - starlette >=0.18.0
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            - strawberry.asgi
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with asgi)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-debug
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - libcst >=0.4.7
        - rich >=12.0.0
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            # TODO: import test for debug
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with debug)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-debug-server
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - libcst >=0.4.7
        - pygments 2.*
        - python-multipart >=0.0.7
        - rich >=12.0.0
        - starlette >=0.18.0
        - typer >=0.7.0
        - uvicorn >=0.11.6
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            # TODO: import test for debug-server
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with debug-server)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-django
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - asgiref 3.*
        - django >=3.2
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            - strawberry.django
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with django)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-channels
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - asgiref 3.*
        - channels >=3.0.5
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            - strawberry.channels
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with channels)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-flask
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - flask >=1.1
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            - strawberry.flask
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with flask)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-quart
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - quart >=0.19.3
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            - strawberry.quart.views
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with quart)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-opentelemetry
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - opentelemetry-api <2
        - opentelemetry-sdk <2
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            - strawberry.extensions.tracing
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with opentelemetry)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-pydantic
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - pydantic >1.6.1
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            - strawberry.experimental.pydantic
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with pydantic)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-sanic
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - sanic >=20.12.2
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            - strawberry.sanic
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with sanic)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-fastapi
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - fastapi >=0.65.2
        - python-multipart >=0.0.7
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            - strawberry.fastapi
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with fastapi)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-chalice
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - chalice 1.*
    tests:
      - python:
          pip_check: false
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            - strawberry.chalice
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with chalice)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-cli
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - libcst >=0.4.7
        - pygments 2.*
        - rich >=12.0.0
        - typer >=0.7.0
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            - strawberry.cli
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - strawberry --help
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with cli)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-litestar
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - litestar >=2
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            - strawberry.litestar
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with litestar)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs

  - package:
      name: strawberry-graphql-with-pyinstrument
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("strawberry-graphql", upper_bound="x.x.x") }}
        - pyinstrument >=4.0.0
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - strawberry
            - strawberry.extensions.pyinstrument
    about:
      homepage: https://strawberry.rocks
      summary: A library for creating GraphQL APIs (with pyinstrument)
      license: MIT
      license_file: LICENSE
      repository: https://github.com/strawberry-graphql/strawberry
      documentation: https://strawberry.rocks/docs


about:
  homepage: https://strawberry.rocks
  summary: A library for creating GraphQL APIs
  license: MIT
  license_file: LICENSE
  repository: https://github.com/strawberry-graphql/strawberry
  documentation: https://strawberry.rocks/docs

extra:
  feedstock-name: strawberry-graphql
  recipe-maintainers:
    - cshaley
    - thewchan
    - bollwyvl
